### PR TITLE
Issue #2- Create github action for this service

### LINKED ISSUE #2: Create github action for this service
- check for all makefile targets 
- check for certain files 

... make this is as autonomous as possible

### PR DESCRIPTION
**Pull request by adhishreekadam**
Checking for all makefile targets and checking for certain files in the repo.

### CODE REVIEW

**Review by joewxboy — APPROVED** [review]
This certainly appears correct.  Were you able to run it on your fork in your personal repo?

**Comment by joewxboy** [comment]
@t-fine If you approve, please merge.

**Comment by adhishreekadam** [comment]
> This certainly appears correct. Were you able to run it on your fork in your personal repo?

Yes, I tested the possible outcomes on my forked repo.

**Review by t-fine — APPROVED** [review]
Awesome, great job! This looks like it will make a model for the other `open-horizon-services` to use going forward 👍🏻

**Pull request merged**
